name: Update Instagram Feed V2

on:
  schedule:
    # Runs at 6:00 AM and 6:00 PM UTC
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-instagram:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build:v2
      
      - name: Update Instagram feed
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        run: npm run update-instagram:v2
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/instagram-v2.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Instagram feed" && git push) 