name: Update Instagram Feed V2

on:
  schedule:
    # Runs at 6:00 AM and 6:00 PM UTC
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-instagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Gives permission to push changes
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the automatic GitHub token
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build:v2
      
      - name: Update Instagram feed
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        run: npm run update-instagram:v2
      
      - name: Commit and push if changed
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/instagram-v2.json images/instagram/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Instagram feed" && git push)

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DREAMHOST_SSH_KEY }}

      - name: Deploy to DreamHost
        env:
          DREAMHOST_HOST: ${{ secrets.DREAMHOST_HOST }}
          DREAMHOST_USERNAME: ${{ secrets.DREAMHOST_USERNAME }}
        run: |
          # Create the remote directory structure
          ssh -o StrictHostKeyChecking=no $DREAMHOST_USERNAME@$DREAMHOST_HOST "mkdir -p /home/brizol/z-photography.com/images/instagram"
          
          # Deploy the updated files
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            data/instagram-v2.json \
            $DREAMHOST_USERNAME@$DREAMHOST_HOST:/home/brizol/z-photography.com/data/
          
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            images/instagram/ \
            $DREAMHOST_USERNAME@$DREAMHOST_HOST:/home/brizol/z-photography.com/images/instagram/ 